---
# Tasks to configure MongoDB service
- name: Ensure MongoDB image is used in Docker Compose
  lineinfile:
    path: "{{ docker_compose_file }}"
    regexp: '^(\s*image:\s*mongo).*'
    line: "    image: {{ mongodb_image }}"
    backrefs: yes

- name: Verify MongoDB port configuration
  lineinfile:
    path: "{{ docker_compose_file }}"
    regexp: '^(\s*-\s*")\d+:(\d+)("\s*#\s*mongodb\s*port.*)'
    line: '    - "{{ mongodb_port }}:\2"\3'
    backrefs: yes
