# Docker Compose file for deploying the backend and MongoDB microservices
version: "3.7"

services:
  # Configures the backend service
  mulikevs-yolo-backend:
    # Specifies the Docker image to use
    image: mulikevs/mulikevs-yolo-backend:v1.0.0
    build: ./backend
    container_name: mulikevs-yolo-backend
    stdin_open: true
    tty: true
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - app-ip-mongo
    # Connects to the shared network
    networks:
      - app-net

  # Configures the MongoDB database service
  app-ip-mongo:
    image: mongo
    container_name: app-mongo
    ports:
      - "27017:27017"
    networks:
      - app-net
    # Persists MongoDB data using a volume
    volumes:
      - type: volume
        source: app-mongo-data
        target: /data/db

# Configures the network for communication between services
networks:
  app-net:
    name: app-net
    driver: bridge
    attachable: true
    ipam:
      config:
        - subnet: 172.20.0.0/16
          ip_range: 172.20.0.0/16

# Defines a volume for persistent MongoDB data
volumes:
  app-mongo-data:
    driver: local
