# Kubernetes manifest for deploying the frontend microservice
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mulikevs-yolo-client
  labels:
    app: mulikevs-yolo-client
spec:
  # Deployment Configuration
  replicas: 1
  selector:
    matchLabels:
      app: mulikevs-yolo-client
  template:
    metadata:
      labels:
        app: mulikevs-yolo-client
    spec:
      # Container Configuration
      containers:
      - name: mulikevs-yolo-client
        image: mulikevs/mulikevs-yolo-client:v1.0.0
        ports:
        - containerPort: 3000
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
---
# Service Configuration
apiVersion: v1
kind: Service
metadata:
  name: mulikevs-yolo-client
spec:
  selector:
    app: mulikevs-yolo-client
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP
