- name: Provision Vagrant VM for e-commerce application
  hosts: all
  become: true
  vars_files:
    - vars.yml

  tasks:
    - name: Debug pathtoyolo
      debug:
        msg: "pathtoyolo is {{ pathtoyolo }}"