# Playbook to provision Vagrant VM for e-commerce application
- name: Provision e-commerce application
  hosts: all
  become: true
  vars_files:
    - vars.yml
 

  roles:
    # Install Docker and Docker Compose
    - docker_install
    # Configure and deploy frontend service
    - frontend_deploy
    # Configure and deploy backend service
    - backend_deploy
    # Configure MongoDB service
    - mongodb_deploy