# Playbook to provision Vagrant VM for e-commerce application
- name: Provision e-commerce application
  hosts: all
  become: true
  vars_files:
    - vars.yml
 
  roles:
    # Install Docker and Docker Compose
    - docker
    # Configure and deploy frontend service
    - frontend
    # Configure and deploy backend service
    - backend
    # Configure MongoDB service
    - mongodb