apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-backend
  namespace: yolo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo-backend
  template:
    metadata:
      labels:
        app: yolo-backend
    spec:
      containers:
      - name: yolo-backend
        image: mulikevs/mulikevs-yolo-backend:v1.0.1
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: "mongodb://mongo:27017/yolomy"
