apiVersion: v1
kind: Service
metadata:
  name: yolo-client
  namespace: yolo-app
spec:
  selector:
    app: yolo-client
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30001
  type: NodePort