apiVersion: v1
kind: Service
metadata:
  name: yolo-client
  namespace: yolo-app
spec:
  selector:
    app: yolo-client
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer