---
# Tasks for common system configuration and dependencies
- name: Test Connectivity
  ping:

- name: Update and upgrade package lists
  apt:
    update_cache: yes
    upgrade: dist
    state: present

- name: Install dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present

- name: Install pip3 (package manager for Python 3)
  apt:
    name: python3-pip
    state: present

- name: Install Python Docker client
  pip:
    name: docker
    state: present

- name: Installing dependencies
  package:
    name: "{{ item }}"
    state: present
    update_cache: yes
  loop:
    - curl
    - gnupg
    - python3-pip
  become: true

- name: Install pymongo
  pip:
    name: pymongo
